[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OC-Project-13-Python-OC-Lettings-FR"
authors = [{name = "Aiswarya Kaitheri Kandoth", email = "graziella@lumache"}]
dynamic = ["version", "description"]
